version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-vol:/var/lib/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - italian-cards-network

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=italian-cards-db
    volumes:
      - mongo-vol:/data/db
    restart: on-failure
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - italian-cards-network

networks:
  italian-cards-network:
    driver: bridge
volumes:
  redis-vol: {}
  mongo-vol:
    driver: local